global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-1:5556', 'kafka-2:5557', 'kafka-3:5558']
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
